baseurl                  = "/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "rad·i·cal"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "dom·i·cile"                           # What to call the home page link
    footerText           = "words can build rad·i·cal things"

# Metadata for Open Graph and Twitter
    description          = "a place to park some words"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "rad·i·cal"

[[params.mainMenu]]
    link = "/poems"
    text = "po·ems"

[[params.mainMenu]]
    link = "/stories"
    text = "sto·ries"

[[params.mainMenu]]
    link = "/pictures"
    text = "pic·tures"

[[params.mainMenu]]
    link = "/about"
    text = "au·thor"

[imaging]
    quality = 75
